site_name: No1Tutoring
repo_url: https://github.com/haoweiqiu/No1Tutoring
nav:
    - Home: 'index.md'
    - User Documentation: 'User Documentation.md'
    - System Requirements Analysis: 'website-requirements.md'
    - Use Case Specification: 'use-case-specification.md'
    - Architecture Model: 'architecture-model.md'
    - Class Diagram: 'class-diagram.md'
    - Extra Features: 'extra.md'
    - REST API Controller Integration Test: 'REST Controller Integration Test.md'
    - REST API Service Specification: 'REST Link.md'
    - Software Quality Assurance Report: 'Software Quality Assurance Report.md'
    - Use Case Diagram: 'Use Case Diagram.md'

theme: readthedocs